services:
  - type: web
    name: DeliveryAi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn DeliveryAi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DeliveryAi.settings
