services:
  - type: web
    name: deliveryai
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn DeliveryAi.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DeliveryAi.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value: your_secret_key_here
      - key: DEBUG
        value: false
